config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get "profile", to: "devise/registrations#edit"
  end

  resources :reservations

  resources :users do
    resources :reservations
  end

  get 'privacy', to: 'static#privacy'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # You can have the root of your site routed with "root"
  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  has_many :passengers, inverse_of: :reservation, autosave: true, dependent: :destroy
  has_many :flights, inverse_of: :reservation, autosave: true, dependent: :destroy
  has_many :checkins, through: :flights, dependent: :destroy
  accepts_nested_attributes_for :user

  before_validation :retrieve_reservation, on: :create
  before_create :create_passengers
  before_create :create_flights
  before_save :upcase_confirmation_number
  after_create :schedule_checkins
  after_commit :send_new_reservation_email, on: :create

  validates_associated :passengers
  validates :confirmation_number, length: { is: 6 }
  validates :confirmation_number,
            :first_name,
            :last_name,
            :payload,
            presence: true

  scope :ordered_by_departure_time, -> { includes(:flights).order("flights.departure_time") }

  def departure_flights
    flights.departure.order(:departure_time)
  end

  def return_flights
    flights.return.order(:departure_time)
  end

  def time
    departure_flights.any? ? departure_flights.first.departure_time : nil
  end

  def international?
    payload['body'] ? payload['body']['isInternationalPNR'] == 'true' : false
  end

  def checkins_completed?
    checkins.count == checkins.completed.count
  end

  private

  def upcase_confirmation_number
    self.confirmation_number = self.confirmation_number.upcase
  end

  def retrieve_reservation
    retrieved_reservation = southwest_reservation

    if retrieved_reservation.error?
      invalidate_reservation(retrieved_reservation)
      return false
    end

    if retrieved_reservation.international?
      errors[:base] << "Unfortunately, do to uncontrolled limitations of the checkin process, international flights are not yet supported."
    end

    self.payload = retrieved_reservation.to_hash
    self.arrival_city_name = retrieved_reservation.arrival_city_name
  end

  def create_passengers
    passengers_attributes = PassengersParser.new(southwest_reservation.body).passengers

    passengers_attributes.each do |passenger_attributes|
      passengers.new(passenger_attributes)
    end
  end

  def create_flights
    flights_attributes = FlightsParser.new(southwest_reservation.body).flights

    flights_attributes.each do |flight_attributes|
      flights.new(flight_attributes)
    end
  end

  def southwest_reservation
    @southwest_reservation ||= Southwest::Reservation.retrieve_reservation(
      last_name: last_name,
      first_name: first_name,
      record_locator: confirmation_number
    )
  end

  def schedule_checkins
    flights.where(position: 1).where("departure_time > ?", Time.zone.now).each do |flight|
      flight.schedule_checkin
    end
  end

  def invalidate_reservation(response)
    if response.entered_incorrectly?
      errors.add(:confirmation_number, 'verify your confirmation number is entered correctly')
      errors.add(:first_name, 'verify your first name is entered correctly')
      errors.add(:last_name, 'verify your last name is entered correctly')
    elsif response.cancelled?
      errors[:base] << "Your reservation has been cancelled"
    else
      errors[:base] << response.error
    end
  end

  def send_new_reservation_email
    ReservationMailer.new_reservation(self).deliver_later
  end
end

app/controllers/reservations_controller.rb
require_relative '../../lib/southwest/errors'

class ReservationsController < ApplicationController
  before_action :authenticate_or_redirect_to_signup!, only: :new
  before_action :authenticate_user!, except: :new
  before_action :current_user_only!
  before_action :set_user, only: [:index, :create]
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  rescue_from Southwest::RequestError, with: :southwest_request_error, only: :create

  respond_to :html

  def index
    @reservations = reservations
    respond_with(@reservations)
  end

  def show
    respond_with(@reservation)
  end

  def new
    @reservation = Reservation.new
    respond_with(@reservation)
  end

  def edit
  end

  def create
    @reservation = @user.reservations.new(reservation_params)
    @reservation.save
    if @reservation.valid?
      flash[:notice] = 'Your reservation has been added! You will receive an email when the passengers on this reservation have been successfully checked in.'
    end
    respond_with(@reservation)
  end

  def update
    @reservation.update(reservation_params)
    respond_with(@reservation)
  end

  def destroy
    @reservation.destroy
    respond_with(@reservation)
  end

  private

  def reservations
    if current_user.admin? && show_all?
      Reservation.page(params[:page])
    else
      @user.reservations.page(params[:page])
    end
  end

  def show_all?
    params[:all] == 'true'
  end

  def authenticate_or_redirect_to_signup!
    if user_signed_in?
      return true
    else
      flash[:notice] = 'Start by creating an account to track your reservations.'
      flash[:from_reservations] = true
      redirect_to new_registration_path(User.new)
    end
  end

  def southwest_request_error
    flash[:notice] = 'Sorry! There was an error communicating with Southwest. This has been reported. Please try to add your flight later.'
    respond_with(@reservation)
  end

  def set_user
    @user = params[:user_id] ? User.find(params[:user_id]) : current_user
  end

  def set_reservation
    @reservation = Reservation.includes({ flights: [{ passenger_checkins: [:passenger] }, :departure_airport, :arrival_airport] }, :passengers).find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:confirmation_number, :first_name, :last_name)
  end

  def current_user_only!
    if !current_user.admin? && params[:id] && Reservation.find(params[:id]).user_id != current_user.id
      raise ActionController::RoutingError.new('Not Found')
    end

    super(params[:user_id])
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def flight_time(local_time)
    time_tag local_time, local_time.strftime('%l:%M %p %Z')
  end

  def flight_date(local_time)
    time_tag local_time, local_time.strftime('%a, %b %d')
  end

  def flight_time_basic(local_time)
    time_tag local_time, local_time.strftime('%l:%M %p')
  end
end

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2>There was a problem retrieving your reservation. Please check the following fields to make sure they are correct:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="FieldGroupTitle">Add a Reservation</div>
  <div class="FieldGroup js-FieldGroup">
    <div class="field">
      <%= f.label 'Confirmation #' %>
      <%= f.text_field :confirmation_number, maxlength: 6, autofocus: true, placeholder: 'Confirmation #', class: 'ConfirmationNumberField' %>
    </div>
    <div class="field">
      <%= f.label 'First Name' %>
      <%= f.text_field :first_name, placeholder: 'First Name' %>
    </div>
    <div class="field">
      <%= f.label 'Last Name' %>
      <%= f.text_field :last_name, placeholder: 'Last Name' %>
    </div>
  </div>

  <!-- div class="FieldGroupTitle">Account</div>
  <div class="FieldGroup js-FieldGroup">
    <%= f.fields_for :user do |ff| %>
      <div class="field">
        <%= ff.label :email %>
        <%= ff.email_field :email %>
      </div>

      <div class="field">
        <%= ff.label :password %>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= ff.password_field :password, autocomplete: "off" %>
      </div>

      <div class="field">
        <%= ff.label :password_confirmation %>
        <%= ff.password_field :password_confirmation, autocomplete: "off" %>
      </div>
    <% end %>
  </div -->

  <div class="actions">
    <%= f.submit 'Add Reservation', class: 'BlueSubmitButton' %>
  </div>
<% end %>

app/views/reservations/_reservation_row.html.erb
<tr>
  <td><%= link_to reservation.confirmation_number, reservation %></td>
  <td><%= flight_date(reservation.time) if reservation.time %></td>
  <td><%= reservation.arrival_city_name %></td>
  <td class='Table-no-mobile'>
    <% if reservation.passengers.one? %>
      <%= reservation.passengers.first.full_name %>
    <% else %>
      <%= reservation.passengers.first.full_name %> + <%= reservation.passengers.count - 1 %>
    <% end %>
  </td>
  <td class="Reservations-checkins <%= reservation.checkins_completed? ? 'Reservations-checkins--success' : '' %>">
    <% if reservation.checkins_completed? %>
      <span class="Icon-checkmark Icon--tiny Icon--padded-right"></span>
    <% end %>
    <span class=<%= reservation.checkins.completed.count > 0 ? 'Reservations-checkins--success' : '' %>>
      <%= reservation.checkins.completed.count %>
    </span> / <%= reservation.checkins.count %>
  </td>
</tr>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<div class="Reservations">
  <table class="Table">
    <thead>
      <tr>
        <th>Confirmation<span class='Table-no-mobile'> number</span></th>
        <th>Date</th>
        <th>Traveling to</th>
        <th class='Table-no-mobile'>Passengers</th>
        <th>Checkins</th>
      </tr>
    </thead>

    <tbody>
      <% @reservations.each do |reservation| %>
        <%= render 'reservations/reservation_row', reservation: reservation %>
      <% end %>
      <% if @reservations.empty? %>
        <tr>
          <td><strong>You have no reservations.</strong></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <div class="Reservations-actions">
    <%= paginate @reservations %>
    <%= link_to 'Add a Reservation', new_reservation_path, class: 'GhostButtonLink' %>
  </div>
</div>

app/views/reservations/new.html.erb
<%= render 'form' %>

app/views/reservations/show.html.erb
<div class="Reservation">
  <div class="ReservationCard">
    <div class="ReservationCard-header ReservationCard-indention-top">
      <div class="ReservationCard-passengers">
        <div class="ReservationCard-label">Passengers</div>
        <% @reservation.passengers.each do |passenger| %>
          <div class="ReservationCard-passenger">
            <%= passenger.full_name %>
          </div>
        <% end %>
      </div>
      <div class="ReservationCard-confirmation-number-group">
        <div class="ReservationCard-label ReservationCard-confirmation-number-label">Confirmation #</div>
        <div class="ReservationCard-confirmation-number"><%= @reservation.confirmation_number %></div>
      </div>
    </div>
    <div class="ReservationCard-flight-groups ReservationCard-indention-bottom">
      <% if @reservation.flights.any? %>
        <% if @reservation.departure_flights.any? %>
          <div class="ReservationCard-flights">
            <div class="ReservationCard-flight-group-title">Departure</div>
            <% @reservation.departure_flights.each do |flight| %>
              <div class="ReservationCard-flight">
                <div class="ReservationCard-flight-title">
                  <%= flight.departure_airport.iata %>
                  <span class="Icon-plane-arrow Icon--large Icon--padded light"></span>
                  <%= flight.arrival_airport.iata %> <span class='u-text-padded'>·</span> <%= flight_date flight.local_departure_time %>
                </div>
                <div class="ReservationCard-flight-details">
                  <div class="ReservationCard-flight-details-group">
                    <div class="ReservationCard-label">Flight No</div>
                    <div class="ReservationCard-flight-number">
                      <%= flight.flight_number %>
                    </div>
                  </div>
                  <div class="ReservationCard-flight-details-group">
                    <div class="ReservationCard-label">Departs</div>
                    <div class="ReservationCard-flight-times-depart">
                      <%= flight_time flight.local_departure_time %>
                    </div>
                  </div>
                  <div class="ReservationCard-flight-details-group">
                    <div class="ReservationCard-label">Arrives</div>
                    <div class="ReservationCard-flight-times-arrive">
                      <%= flight_time flight.local_arrival_time %>
                    </div>
                  </div>
                  <% if flight.passenger_checkins.any? %>
                    <div class="ReservationCard-flight-checkins">
                      <% flight.passenger_checkins.each do |passenger_checkin| %>
                        <div class="ReservationCard-flight-checkin">
                          <span class="Icon-checkmark Icon--tiny Icon--padded-right"></span>
                          <span class="ReservationCard-badge u-text-padded-right"><%= passenger_checkin.boarding_group %><%= passenger_checkin.boarding_position %></span>
                          <%= passenger_checkin.passenger.full_name %>
                        </div>
                      <% end %>
                    </div>
                  <% end %>
                  <% if flight.scheduled? %>
                    <div class="ReservationCard-scheduled">
                        <span class='Icon-clock Icon--smallest'></span> Automatic checkin at <%= flight_time_basic flight.checkin.local_scheduled_at %> <%= flight_date flight.checkin.local_scheduled_at %>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
        <% if @reservation.return_flights.any? %>
          <div class="ReservationCard-flights">
            <div class="ReservationCard-flight-group-title">Return</div>
            <% @reservation.return_flights.each do |flight| %>
              <div class="ReservationCard-flight">
                <div class="ReservationCard-flight-title">
                  <%= flight.departure_airport.iata %>
                  <span class="Icon-plane-arrow Icon--large Icon--padded light"></span>
                  <%= flight.arrival_airport.iata %> <span class='u-text-padded'>·</span> <%= flight_date flight.local_departure_time %>
                </div>
                <div class="ReservationCard-flight-details">
                  <div class="ReservationCard-flight-details-group">
                    <div class="ReservationCard-label">Flight No</div>
                    <div class="ReservationCard-flight-number">
                      <%= flight.flight_number %>
                    </div>
                  </div>
                  <div class="ReservationCard-flight-details-group">
                    <div class="ReservationCard-label">Departs</div>
                    <div class="ReservationCard-flight-times-depart">
                      <%= flight_time flight.local_departure_time %>
                    </div>
                  </div>
                  <div class="ReservationCard-flight-details-group">
                    <div class="ReservationCard-label">Arrives</div>
                    <div class="ReservationCard-flight-times-arrive">
                      <%= flight_time flight.local_arrival_time %>
                    </div>
                  </div>
                  <% if flight.passenger_checkins.any? %>
                    <div class="ReservationCard-flight-checkins">
                      <% flight.passenger_checkins.each do |passenger_checkin| %>
                        <div class="ReservationCard-flight-checkin">
                          <span class="Icon-checkmark Icon--tiny Icon--padded-right"></span>
                          <span class="ReservationCard-badge u-text-padded-right"><%= passenger_checkin.boarding_group %><%= passenger_checkin.boarding_position %></span>
                          <%= passenger_checkin.passenger.full_name %>
                        </div>
                      <% end %>
                    </div>
                  <% end %>
                  <% if flight.scheduled? %>
                    <div class="ReservationCard-scheduled">
                        <span class='Icon-clock Icon--smallest'></span> Automatic checkin at <%= flight_time_basic flight.checkin.local_scheduled_at %> <%= flight_date flight.checkin.local_scheduled_at %>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% elsif @reservation.international? %>
        <p class='ReservationCard-message'>
          Unfortunately, do to uncontrolled limitations of the checkin process, international flights are not yet supported.
        </p>
      <% else %>
        No flights.
      <% end %>
    </div>
  </div>
  <div class='ReservationCard-footer'>
    <%= link_to 'Remove Reservation', @reservation, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>